### ISSUE TITLE
GraphQl Request :Free Text Dynamic Mapping

### ISSUE THREAD

**Issue by sharmmoh1983** [graphql-java/graphql-spring-boot#123]
Hi 
 My front end API is calling backend graphql api so I need to convert front end plain/text request to graphql plain/request but this seems to be a challenge in writing  dynamic plain text request to request mapping.

Does any one have any idea to get the work around

**Comment by oliemansm** [comment]
Can you provide example code and requests to better explain what you mean? I have absolutely no clue what you're talking about here :-)

**Comment by sharmmoh1983** [comment]
@oliemansm 

Please find the following scenario:

Front end api graphql Request:
```
{
  getAllDetails{
  Person {
   name
Address{
  city
}
}
}
}
```

Backend Graphql request:
```
{
  getAllDetails{
  name
  city
}
}
```
I have implemented backend  API as graphql which talks to the database as per the Database schema which is flat object

Now in my framework, I will be creating  front end wrapper apis which will eventually call backed rest api 

 Schema for all front end api will not be same as backend so I have to do mapping of free text to free text request and also the response mapping which is easy as it will be json message 

So I need a pattern in which I can have  multiple front api with their respective free text request which call one graphql implmented api 

But I am facing the challenge to do text to text mapping. 
So what should be the right way to achieve the same

**Comment by oliemansm** [comment]
I suggest you send the request to StackOverflow instead. This isn't related to spring boot or graphql specifically, but seems to be a more general / architecture type question. When you create the issue at StackOverflow I advice you to add some examples of the actual mapping you think you need to do and why. From this explanation it's still not clear to me at least, so unless you find a way to explain very clearly what you're trying to achieve you'll have a hard time find the right help.

I know that in your mind it's probably very clear, but it's not to an outsider.
